# Clustering STORE_NEW_DATASET

### Notebook automatically generated from your model

Model KMeans (k=7) (s8), trained on 2023-07-12 09:14:09.

#### Generated on 2023-07-12 17:07:53.238997

Clustering
This notebook will reproduce the steps for clustering the dataset STORE_NEW_DATASET.

#### Warning

The goal of this notebook is to provide an easily readable and explainable code that reproduces the main steps
of training the model. It is not complete: some of the preprocessing done by the DSS visual machine learning is not
replicated in this notebook. This notebook will not give the same results and model performance as the DSS visual machine
learning model.

Let's start with importing the required libs :

In [1]:
import sys
import dataiku
import numpy as np
import pandas as pd
import sklearn as sk
import dataiku.core.pandasutils as pdu
from dataiku.doctor.preprocessing import PCA
from collections import defaultdict, Counter

And tune pandas display options:

In [2]:
pd.set_option('display.width', 3000)
pd.set_option('display.max_rows', 200)
pd.set_option('display.max_columns', 200)

#### Importing base data

The first step is to get our machine learning dataset:

In [3]:
# We apply the preparation that you defined. You should not modify this.
preparation_steps = []
preparation_output_schema = {'columns': [{'name': 'Unnamed: 0', 'type': 'bigint'}, {'name': 'cod_tienda', 'type': 'bigint'}, {'name': 'promocion_cabecera', 'type': 'bigint'}, {'name': 'promocion_descuento', 'type': 'bigint'}, {'name': 'promocion_expositor', 'type': 'bigint'}, {'name': 'promocion_extra_cantidad', 'type': 'bigint'}, {'name': 'promocion_folleto', 'type': 'bigint'}, {'name': 'promocion_isla', 'type': 'bigint'}, {'name': 'promocion_multicompra', 'type': 'bigint'}, {'name': 'promocion_regalo', 'type': 'bigint'}, {'name': 'factor_extrapolacion', 'type': 'bigint'}, {'name': 'cod_canal', 'type': 'bigint'}, {'name': 'national_holidays_2021', 'type': 'bigint'}, {'name': 'regional_holidays_2021', 'type': 'bigint'}, {'name': 'local_holidays_2021', 'type': 'bigint'}, {'name': 'national_holidays_2022', 'type': 'bigint'}, {'name': 'regional_holidays_2022', 'type': 'bigint'}, {'name': 'local_holidays_2022', 'type': 'bigint'}, {'name': 'national_holidays_2023', 'type': 'bigint'}, {'name': 'regional_holidays_2023', 'type': 'bigint'}, {'name': 'local_holidays_2023', 'type': 'bigint'}, {'name': 'SEGMENT_ARTISANS_x', 'type': 'bigint'}, {'name': 'SEGMENT_BLACK_x', 'type': 'bigint'}, {'name': 'SEGMENT_CELIACS_x', 'type': 'bigint'}, {'name': 'SEGMENT_EXTRA_x', 'type': 'bigint'}, {'name': 'SEGMENT_FLAVOURED_x', 'type': 'bigint'}, {'name': 'SEGMENT_IMPORT PREMIUM_x', 'type': 'bigint'}, {'name': 'SEGMENT_IMPORT SPECIAL_x', 'type': 'bigint'}, {'name': 'SEGMENT_NATIONAL_x', 'type': 'bigint'}, {'name': 'SEGMENT_WITHOUT ALCOHOL_x', 'type': 'bigint'}, {'name': 'SEGMENT_ZERO ALCOHOL_x', 'type': 'bigint'}, {'name': 'MANUFACTURER_MANUFACTURER 1', 'type': 'bigint'}, {'name': 'MANUFACTURER_MANUFACTURER 2', 'type': 'bigint'}, {'name': 'MANUFACTURER_MANUFACTURER 3', 'type': 'bigint'}, {'name': 'MANUFACTURER_MANUFACTURER 4', 'type': 'bigint'}, {'name': 'MANUFACTURER_MANUFACTURER 5', 'type': 'bigint'}, {'name': 'MANUFACTURER_MANUFACTURER 6', 'type': 'bigint'}, {'name': 'MANUFACTURER_OTHER MANUFACTURERS', 'type': 'bigint'}, {'name': 'BRAND_MAN 1 - BRAND 1', 'type': 'bigint'}, {'name': 'BRAND_MAN 1 - BRAND 2', 'type': 'bigint'}, {'name': 'BRAND_MAN 1 - OTHER BRANDS', 'type': 'bigint'}, {'name': 'BRAND_MAN 2 - BRAND 1', 'type': 'bigint'}, {'name': 'BRAND_MAN 2 - BRAND 2', 'type': 'bigint'}, {'name': 'BRAND_MAN 2 - BRAND 3', 'type': 'bigint'}, {'name': 'BRAND_MAN 2 - BRAND 4', 'type': 'bigint'}, {'name': 'BRAND_MAN 2 - BRAND 5', 'type': 'bigint'}, {'name': 'BRAND_MAN 2 - OTHER BRANDS', 'type': 'bigint'}, {'name': 'BRAND_MAN 3 - BRAND 1', 'type': 'bigint'}, {'name': 'BRAND_MAN 3 - BRAND 2', 'type': 'bigint'}, {'name': 'BRAND_MAN 3 - BRAND 3', 'type': 'bigint'}, {'name': 'BRAND_MAN 3 - BRAND 4', 'type': 'bigint'}, {'name': 'BRAND_MAN 3 - BRAND 5', 'type': 'bigint'}, {'name': 'BRAND_MAN 3 - OTHER BRANDS', 'type': 'bigint'}, {'name': 'BRAND_MAN 4 - BRAND 1', 'type': 'bigint'}, {'name': 'BRAND_MAN 5 - BRAND 1', 'type': 'bigint'}, {'name': 'BRAND_MAN 5 - BRAND 2', 'type': 'bigint'}, {'name': 'BRAND_MAN 5 - OTHER BRANDS', 'type': 'bigint'}, {'name': 'BRAND_MAN 6 - BRAND 1', 'type': 'bigint'}, {'name': 'BRAND_OTHER MAN - OTHER BRANDS', 'type': 'bigint'}, {'name': 'PACKAGING_CAN', 'type': 'bigint'}, {'name': 'PACKAGING_CRISTAL BOTTLE', 'type': 'bigint'}, {'name': 'PACKAGING_OTHER', 'type': 'bigint'}, {'name': 'PACKAGING_PET', 'type': 'bigint'}, {'name': 'MAN 1 - BRAND 1', 'type': 'double'}, {'name': 'MAN 1 - BRAND 2', 'type': 'double'}, {'name': 'MAN 1 - OTHER BRANDS', 'type': 'double'}, {'name': 'MAN 2 - BRAND 1', 'type': 'double'}, {'name': 'MAN 2 - BRAND 2', 'type': 'double'}, {'name': 'MAN 2 - BRAND 3', 'type': 'double'}, {'name': 'MAN 2 - BRAND 4', 'type': 'double'}, {'name': 'MAN 2 - BRAND 5', 'type': 'double'}, {'name': 'MAN 2 - OTHER BRANDS', 'type': 'double'}, {'name': 'MAN 3 - BRAND 1', 'type': 'double'}, {'name': 'MAN 3 - BRAND 2', 'type': 'double'}, {'name': 'MAN 3 - BRAND 3', 'type': 'double'}, {'name': 'MAN 3 - BRAND 4', 'type': 'double'}, {'name': 'MAN 3 - BRAND 5', 'type': 'double'}, {'name': 'MAN 3 - OTHER BRANDS', 'type': 'double'}, {'name': 'MAN 4 - BRAND 1', 'type': 'double'}, {'name': 'MAN 5 - BRAND 1', 'type': 'double'}, {'name': 'MAN 5 - BRAND 2', 'type': 'double'}, {'name': 'MAN 5 - OTHER BRANDS', 'type': 'double'}, {'name': 'MAN 6 - BRAND 1', 'type': 'double'}, {'name': 'OTHER MAN - OTHER BRANDS', 'type': 'double'}, {'name': 'SEGMENT_ARTISANS_y', 'type': 'double'}, {'name': 'SEGMENT_BLACK_y', 'type': 'double'}, {'name': 'SEGMENT_CELIACS_y', 'type': 'double'}, {'name': 'SEGMENT_EXTRA_y', 'type': 'double'}, {'name': 'SEGMENT_FLAVOURED_y', 'type': 'double'}, {'name': 'SEGMENT_IMPORT PREMIUM_y', 'type': 'double'}, {'name': 'SEGMENT_IMPORT SPECIAL_y', 'type': 'double'}, {'name': 'SEGMENT_NATIONAL_y', 'type': 'double'}, {'name': 'SEGMENT_WITHOUT ALCOHOL_y', 'type': 'double'}, {'name': 'SEGMENT_ZERO ALCOHOL_y', 'type': 'double'}, {'name': 'sales_surface_sqmeters', 'type': 'bigint'}, {'name': 'ventas_valor_per_store', 'type': 'double'}, {'name': 'Channel', 'type': 'string'}, {'name': 'revenue_per_sqmeter', 'type': 'double'}, {'name': 'Provincia_x', 'type': 'string'}, {'name': 'Sectors', 'type': 'string'}, {'name': 'cod_provincia', 'type': 'bigint'}, {'name': 'Provincia_y', 'type': 'string'}, {'name': 'Net income per person', 'type': 'string'}, {'name': 'year', 'type': 'bigint'}, {'name': 'Income', 'type': 'bigint'}], 'userModified': False}

ml_dataset_handle = dataiku.Dataset('STORE_NEW_DATASET')
ml_dataset_handle.set_preparation_steps(preparation_steps, preparation_output_schema)
%time ml_dataset = ml_dataset_handle.get_dataframe(limit = 100000)

print ('Base data has %i rows and %i columns' % (ml_dataset.shape[0], ml_dataset.shape[1]))
# Five first records",
ml_dataset.head(5)

CPU times: user 25.4 ms, sys: 6.23 ms, total: 31.6 ms
Wall time: 463 ms
Base data has 543 rows and 105 columns

   Unnamed: 0  cod_tienda  promocion_cabecera  promocion_descuento  promocion_expositor  promocion_extra_cantidad  promocion_folleto  promocion_isla  promocion_multicompra  promocion_regalo  factor_extrapolacion  cod_canal  national_holidays_2021  regional_holidays_2021  local_holidays_2021  national_holidays_2022  regional_holidays_2022  local_holidays_2022  national_holidays_2023  regional_holidays_2023  local_holidays_2023  SEGMENT_ARTISANS_x  SEGMENT_BLACK_x  SEGMENT_CELIACS_x  SEGMENT_EXTRA_x  SEGMENT_FLAVOURED_x  SEGMENT_IMPORT PREMIUM_x  SEGMENT_IMPORT SPECIAL_x  SEGMENT_NATIONAL_x  SEGMENT_WITHOUT ALCOHOL_x  SEGMENT_ZERO ALCOHOL_x  MANUFACTURER_MANUFACTURER 1  MANUFACTURER_MANUFACTURER 2  MANUFACTURER_MANUFACTURER 3  MANUFACTURER_MANUFACTURER 4  MANUFACTURER_MANUFACTURER 5  MANUFACTURER_MANUFACTURER 6  MANUFACTURER_OTHER MANUFACTURERS  BRAND_MAN 1 - BRAND 1  BRAND_MAN 1 - BRAND 2  BRAND_MAN 1 - OTHER BRANDS  BRAND_MAN 2 - BRAND 1  BRAND_MAN 2 - BRAND 2  BRAND_MAN 2 - BRAND 3  BRAND_MAN 2 - BRAND 4  BRAND_MAN 2 - BRAND 5  BRAND_MAN 2 - OTHER BRANDS  BRAND_MAN 3 - BRAND 1  BRAND_MAN 3 - BRAND 2  BRAND_MAN 3 - BRAND 3  BRAND_MAN 3 - BRAND 4  BRAND_MAN 3 - BRAND 5  BRAND_MAN 3 - OTHER BRANDS  BRAND_MAN 4 - BRAND 1  BRAND_MAN 5 - BRAND 1  BRAND_MAN 5 - BRAND 2  BRAND_MAN 5 - OTHER BRANDS  BRAND_MAN 6 - BRAND 1  BRAND_OTHER MAN - OTHER BRANDS  PACKAGING_CAN  PACKAGING_CRISTAL BOTTLE  PACKAGING_OTHER  PACKAGING_PET  MAN 1 - BRAND 1  MAN 1 - BRAND 2  MAN 1 - OTHER BRANDS  MAN 2 - BRAND 1  MAN 2 - BRAND 2  MAN 2 - BRAND 3  MAN 2 - BRAND 4  MAN 2 - BRAND 5  MAN 2 - OTHER BRANDS  MAN 3 - BRAND 1  MAN 3 - BRAND 2  MAN 3 - BRAND 3  MAN 3 - BRAND 4  MAN 3 - BRAND 5  MAN 3 - OTHER BRANDS  MAN 4 - BRAND 1  MAN 5 - BRAND 1  MAN 5 - BRAND 2  MAN 5 - OTHER BRANDS  MAN 6 - BRAND 1  OTHER MAN - OTHER BRANDS  SEGMENT_ARTISANS_y  SEGMENT_BLACK_y  SEGMENT_CELIACS_y  SEGMENT_EXTRA_y  SEGMENT_FLAVOURED_y  SEGMENT_IMPORT PREMIUM_y  SEGMENT_IMPORT SPECIAL_y  SEGMENT_NATIONAL_y  SEGMENT_WITHOUT ALCOHOL_y  SEGMENT_ZERO ALCOHOL_y  sales_surface_sqmeters  ventas_valor_per_store       Channel  revenue_per_sqmeter                   Provincia_x         Sectors  cod_provincia Provincia_y         Net income per person  year  Income
0           0           1                   1                    1                    1                         1                  0               1                      1                 1                     0          1                       1                       1                    1                       0                       0                    0                       0                       0                    0                   0                1                  1                1                    1                         1                         1                   1                          1                       1                            1                            1                            1                            0                            1                            1                                 1                      1                      0                           0                      1                      1                      1                      1                      1                           1                      1                      0                      1                      1                      0                           1                      0                      0                      1                           0                      1                               1              1                         1                0              1     2.093188e+04            0.000                0.0000     3.127363e+04      245808.4237       34296.4296         381.2744        2789.4838            78053.2296       91206.3133           0.0000     7.970274e+04     1.489422e+05              0.0            14577.3146     0.000000e+00           0.0000        1213.6000                0.0000     7.044279e+05                12227.5290              0.0000        1414.6977           421.6480     7.561654e+04           27506.3214              5.310461e+05                 3305.1734        6.300099e+05                 71392.9384             125118.5008                     500                24415.94  Supermarkets            48.831880                       Almeria  Primary Sector              4     Almeria  Renta neta media por persona  2020    9709
1           1           2                   0                    0                    0                         0                  0               0                      0                 0                     0          1                       0                       0                    1                       0                       0                    0                       0                       0                    0                   0                0                  0                1                    0                         0                         0                   0                          0                       0                            0                            0                            1                            0                            0                            0                                 0                      0                      0                           0                      0                      0                      0                      0                      0                           0                      1                      0                      0                      0                      0                           0                      0                      0                      0                           0                      0                               0              0                         1                0              0     0.000000e+00            0.000                0.0000     0.000000e+00           0.0000           0.0000           0.0000           0.0000                0.0000         815.9604           0.0000     0.000000e+00     0.000000e+00              0.0                0.0000     0.000000e+00           0.0000           0.0000                0.0000     0.000000e+00                    0.0000              0.0000           0.0000             0.0000     8.159604e+02               0.0000              0.000000e+00                    0.0000        0.000000e+00                     0.0000                  0.0000                     500                    8.52  Supermarkets             0.017040  Area Metropolitana de Madrid      Metropolis             95      Madrid  Renta neta media por persona  2020   15579
2           2           3                   1                    1                    1                         1                  1               1                      1                 1                     0          1                       1                       1                    1                       1                       1                    1                       1                       1                    1                   1                1                  1                1                    1                         1                         1                   1                          1                       1                            1                            1                            1                            1                            1                            1                                 1                      1                      0                           1                      1                      1                      1                      1                      1                           1                      1                      0                      1                      1                      0                           1                      1                      1                      1                           0                      1                               1              1                         1                1              1     1.027358e+06            0.000           132435.0502     1.270758e+06      406712.9309      896062.5975       38137.5001       79546.7018           364070.1169      645475.2208           0.0000     3.162244e+06     1.942609e+06              0.0           102719.8487     1.586968e+06          82.2500       90054.6162                0.0000     1.083251e+05               852118.1660         181071.9192      126202.5774         62344.3673     2.056731e+06          678890.3149              1.315005e+06               391735.2451        7.045113e+06                369141.4429             479443.2445                    1200               174172.84  Supermarkets           145.144033                     Cantabria      Industrial             39   Cantabria  Renta neta media por persona  2020   12865
3           3           4                   1                    1                    1                         1                  1               1                      1                 1                     0          1                       1                       1                    1                       1                       1                    1                       1                       1                    1                   1                1                  1                1                    1                         1                         1                   1                          1                       1                            1                            1                            1                            1                            1                            1                                 1                      1                      1                           1                      1                      1                      1                      1                      1                           1                      1                      1                      1                      1                      0                           1                      1                      1                      1                           1                      1                               1              1                         1                1              1     1.327195e+05           17.025             8789.1847     9.422291e+04       34089.0494      141834.0120       11071.3784       15241.1026            41484.0975       55629.4502         832.7146     1.199536e+05     2.091851e+05              0.0            28714.5962     1.638660e+05         695.7223       12907.7715               51.7644     5.221909e+04               287779.6831          22195.1685       48411.6924          4216.3742     2.091155e+05           77684.2095              2.629581e+05               150471.2403        5.378297e+05                 40797.3675              57624.5116                    2200               629539.99  Supermarkets           286.154541                       Vizcaya      Industrial             48     Vizcaya  Renta neta media por persona  2020   15555
4           4           5                   0                    1                    1                         1                  1               1                      0                 1                     0          1                       1                       1                    1                       1                       1                    1                       1                       1                    1                   0                0                  1                1                    1                         1                         1                   1                          1                       1                            1                            1                            1                            1                            1                            1                                 1                      1                      0                           1                      1                      1                      1                      0                      1                           1                      1                      0                      1                      1                      0                           0                      1                      0                      1                           0                      1                               1              1                         1                0              1     8.297298e+04            0.000             2650.3022     5.530031e+05       65193.1952       94031.3046           0.0000       41703.5397            64664.9017      114585.5170           0.0000     1.315183e+05     5.700949e+05              0.0                0.0000     7.320569e+04           0.0000        2804.5336                0.0000     1.318352e+06                16696.9154              0.0000           0.0000          2804.5336     1.216046e+05           79013.7463              6.986261e+05                41703.5397        1.931208e+06                143889.3444             112627.8304                     900               151578.07  Supermarkets           168.420078                     Castellon  Primary Sector             12   Castellon  Renta neta media por persona  2020   12079

#### Initial data management

The preprocessing aims at making the dataset compatible with modeling.
At the end of this step, we will have a matrix of float numbers, with no missing values.
We'll use the features and the preprocessing steps defined in Models.

Let's only keep selected features

In [4]:
ml_dataset = ml_dataset[['Sectors', 'Income', 'revenue_per_sqmeter']]

Let's first coerce categorical columns into unicode, numerical features into floats.

In [5]:
# astype('unicode') does not work as expected

def coerce_to_unicode(x):
    if sys.version_info < (3, 0):
        if isinstance(x, str):
            return unicode(x,'utf-8')
        else:
            return unicode(x)
    else:
        return str(x)


categorical_features = ['Sectors']
numerical_features = ['Income', 'revenue_per_sqmeter']
text_features = []
from dataiku.doctor.utils import datetime_to_epoch
for feature in categorical_features:
    ml_dataset[feature] = ml_dataset[feature].apply(coerce_to_unicode)
for feature in text_features:
    ml_dataset[feature] = ml_dataset[feature].apply(coerce_to_unicode)
for feature in numerical_features:
    if ml_dataset[feature].dtype == np.dtype('M8[ns]') or (hasattr(ml_dataset[feature].dtype, 'base') and ml_dataset[feature].dtype.base == np.dtype('M8[ns]')):
        ml_dataset[feature] = datetime_to_epoch(ml_dataset[feature])
    else:
        ml_dataset[feature] = ml_dataset[feature].astype('double')

Let's copy our dataset to keep it for eventual profiling at the end.

In [6]:
# train dataset will be the one on which we will apply ml technics
train = ml_dataset.copy()

#### Features preprocessing

The first thing to do at the features level is to handle the missing values.
Let's reuse the settings defined in the model

In [7]:
drop_rows_when_missing = []
impute_when_missing = [{'feature': 'Income', 'impute_with': 'MEAN'}, {'feature': 'revenue_per_sqmeter', 'impute_with': 'MEAN'}]

# Features for which we drop rows with missing values"
for feature in drop_rows_when_missing:
    train = train[train[feature].notnull()]
    
    print ('Dropped missing records in %s' % feature)

# Features for which we impute missing values"
for feature in impute_when_missing:
    if feature['impute_with'] == 'MEAN':
        v = train[feature['feature']].mean()
    elif feature['impute_with'] == 'MEDIAN':
        v = train[feature['feature']].median()
    elif feature['impute_with'] == 'CREATE_CATEGORY':
        v = 'NULL_CATEGORY'
    elif feature['impute_with'] == 'MODE':
        v = train[feature['feature']].value_counts().index[0]
    elif feature['impute_with'] == 'CONSTANT':
        v = feature['value']
    train[feature['feature']] = train[feature['feature']].fillna(v)
    
    print ('Imputed missing values in feature %s with value %s' % (feature['feature'], coerce_to_unicode(v)))

Imputed missing values in feature Income with value 13061.902394106814
Imputed missing values in feature revenue_per_sqmeter with value 204.16344291633814

We can now handle the categorical features (still using the settings defined in Models):

Let's dummy-encode the following features.
A binary column is created for each of the 100 most frequent values.

In [8]:
LIMIT_DUMMIES = 100

categorical_to_dummy_encode = ['Sectors']

# Only keep the top 100 values
def select_dummy_values(train, features):
    dummy_values = {}
    for feature in categorical_to_dummy_encode:
        values = [
            value
            for (value, _) in Counter(train[feature]).most_common(LIMIT_DUMMIES)
        ]
        dummy_values[feature] = values
    return dummy_values

DUMMY_VALUES = select_dummy_values(train, categorical_to_dummy_encode)

def dummy_encode_dataframe(df):
    for (feature, dummy_values) in DUMMY_VALUES.items():
        for dummy_value in dummy_values:
            dummy_name = u'%s_value_%s' % (feature, coerce_to_unicode(dummy_value))
            df[dummy_name] = (df[feature] == dummy_value).astype(float)
        del df[feature]
        print ('Dummy-encoded feature %s' % feature)

dummy_encode_dataframe(train)

Dummy-encoded feature Sectors

Let's rescale numerical features

In [9]:
rescale_features = {'Income': 'AVGSTD', 'revenue_per_sqmeter': 'AVGSTD'}
for (feature_name, rescale_method) in rescale_features.items():
    if rescale_method == 'MINMAX':
        _min = train[feature_name].min()
        _max = train[feature_name].max()
        scale = _max - _min
        shift = _min
    else:
        shift = train[feature_name].mean()
        scale = train[feature_name].std()
    if scale == 0.:
        del train[feature_name]
        
        print ('Feature %s was dropped because it has no variance' % feature_name)
    else:
        print ('Rescaled %s' % feature_name)
        train[feature_name] = (train[feature_name] - shift).astype(np.float64) / scale

Rescaled Income
Rescaled revenue_per_sqmeter

Removing outliers

In [10]:
# Outliers detection not required, skipping...

#### Modeling

In [11]:
from sklearn.cluster import KMeans
clustering_model = KMeans(n_clusters=7)

We can finally cluster our dataset!

In [12]:
%time clusters = clustering_model.fit_predict(train)

CPU times: user 349 ms, sys: 53.6 ms, total: 403 ms
Wall time: 92.9 ms

Build up our result dataset

#### Results

Inertia

In [13]:
print (clustering_model.inertia_)

361.41455005793694

Silhouette

In [14]:
from sklearn.metrics import silhouette_score
silhouette = silhouette_score(train.values, clusters, metric='euclidean', sample_size=2000)
print ("Silhouette score :", silhouette)

Silhouette score : 0.3856290752647586

Join our original dataset with the cluster labels we found.

In [15]:
final = train.join(pd.Series(clusters, index=train.index, name='cluster'))
final['cluster'] = final['cluster'].map(lambda cluster_id: 'cluster' + str(cluster_id))

Compute the cluster sizes

In [16]:
size = pd.DataFrame({'size': final['cluster'].value_counts()})
size.head()

          size
cluster5   139
cluster2    95
cluster0    93
cluster4    77
cluster3    70

Draw a nice scatter plot

In [18]:
final

       Income  revenue_per_sqmeter  Sectors_value_Industrial  Sectors_value_Metropolis  Sectors_value_Primary Sector  Sectors_value_touristic   cluster
0   -1.801595            -0.794024                       0.0                       0.0                           1.0                      0.0  cluster2
1    1.352497            -1.043556                       0.0                       1.0                           0.0                      0.0  cluster0
2   -0.105800            -0.301696                       1.0                       0.0                           0.0                      0.0  cluster5
3    1.339601             0.419122                       1.0                       0.0                           0.0                      0.0  cluster3
4   -0.528137            -0.182713                       0.0                       0.0                           1.0                      0.0  cluster4
..        ...                  ...                       ...                       ...                           ...                      ...       ...
538 -1.052028             0.628991                       1.0                       0.0                           0.0                      0.0  cluster1
539  1.020968             1.107461                       0.0                       0.0                           0.0                      1.0  cluster3
540  0.867293             0.846160                       0.0                       1.0                           0.0                      0.0  cluster3
541 -0.077860            -0.089834                       0.0                       0.0                           1.0                      0.0  cluster4
542  0.384239             1.033018                       0.0                       0.0                           1.0                      0.0  cluster4

[543 rows x 7 columns]

In [17]:
axis_x = train.columns[0]   # change me
axis_y = train.columns[1]  # change me

from ggplot import ggplot, aes, geom_point
print(ggplot(aes(axis_x, axis_y, colour='cluster'), final) + geom_point())

ModuleNotFoundError: No module named 'ggplot'

That's it. It's now up to you to tune your preprocessing, your algo, and your analysis !